name: an_dialogs
description: "Used to manage route-based dialogs and loading states, controlling when they are pushed and
dismissed."
version: 1.2.0
homepage: https://github.com/aymtools/an_dialog/
issue_tracker: https://github.com/aymtools/an_dialog/issues

topics:
  - loading
  - dialog
  - dialog-manager
  - dialogs

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  cancellable: ^2.4.0
  anlifecycle: ^3.5.1
  weak_collections: ^1.5.0
  an_lifecycle_cancellable: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter: